language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: TYPE=Debug

    - os: linux
      dist: xenial
      sudo: required
      env: TYPE=Release

    - os: osx
      sudo: required
      env: TYPE=Release
 
      
before_install:
  - eval "${MATRIX_EVAL}"
  - git clone https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_packages.sh
  - bash ./emp-readme/scripts/install_relic.sh

script:
  - cmake -DCMAKE_BUILD_TYPE=$TYPE . 
  - while sleep 5m; do echo "=====[ $SECONDS seconds ]====="; done &
  - make 2>&1
  - echo "Testing Basic Primitives"
  - ./bin/prp
  - ./bin/prg
  - ./bin/com
  - ./bin/hash
  - ./bin/garble 1 12345 & ./bin/garble 2 12345
  - ./bin/netio 1 12345 & ./bin/netio 2 12345
  - echo "Testing Circuits"
  - ./bin/bit
  - ./bin/int
  - ./bin/float32
